name: Build & Push OCI Image to OCI Image Registry

on:
  push:
    branches:
      - master

permissions:
  contents: read
  packages: write

jobs:
  x86:
    uses: ./.github/workflows/build.yaml
    with:
      runs-on: '"ubuntu-24.04"'
      platforms: '["linux/386", "linux/amd64", "linux/amd64/v2", "linux/amd64/v3"]'
    secrets: inherit
  arm:
    uses: ./.github/workflows/build.yaml
    with:
      runs-on: '"ubuntu-24.04-arm"'
      platforms: '["linux/arm/v6", "linux/arm/v7", "linux/arm64/v8"]'
    secrets: inherit
  riscv:
    uses: ./.github/workflows/build.yaml
    with:
      runs-on: '"ubuntu-24.04"'
      platforms: '["linux/riscv64"]'
    secrets: inherit
  ppc:
    uses: ./.github/workflows/build.yaml
    with:
      runs-on: '"ubuntu-24.04"'
      platforms: '["linux/ppc64le"]'
    secrets: inherit
  s390:
    uses: ./.github/workflows/build.yaml
    with:
      runs-on: '"ubuntu-24.04"'
      platforms: '["linux/s390x"]'
    secrets: inherit